### PR TITLE
fix: disable changing resource policy name

### LINKED ISSUE #789: Resource Policy name in modification should be disabled.
> ※ NOTICE: This feature is available for admin users or super-admin users only.

**Describe the bug**
As if It seems that Input field of policy name in resource policy modification dialog is writeable, in fact it's not.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. Go to Users page
2. Click on 'RESOURCE POLICIES' tab.
3. click image button in control column of existing policy group in the table.
4. 'Update Resource Policy' dialog appears.
5. change the policy name.
6. click update button in the bottom of the dialog opened in step 4.
7. See the error that policy name didn't change and a snack-bar message that saying 'no matching record'.

**Expected behavior**
If resource policy name is non-changable, UI of that part should be disabled, or read-only.

**Client:**
 - OS: macOS 10.15.6
 - App version: 20.11.0
 - Browser version: Firefox 82.0(64 bit)
 - NodeJS version: 13.8.0

**Server:**
 - OS: macOS 10.15.6
   - Output of `uname -a`: Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
 - Backend.AI version: 20.09.0a2
 - Python version: 3.8.3
 - Installation method: used scripts/install-dev.sh

### PR DESCRIPTION
**Pull request by lizable**
This PR resolves #789.

### CODE REVIEW

File: src/components/backend-ai-resource-policy-list.ts [hunk 1]
```diff
@@ -638,14 +656,23 @@ export default class BackendAIResourcePolicyList extends BackendAIPage {
...
   }
 
-  _deleteKey(e) {
-    const controls = e.target.closest('#controls');
-    const accessKey = controls.accessKey;
-    globalThis.backendaiclient.keypair.delete(accessKey).then(response => {
-      this.refresh();
+  _deleteResourcePolicy() {
+    let name = this.current_policy_name;
+    console.log(this.current_policy_name)
```
Comment (adrysn) [inline src/components/backend-ai-resource-policy-list.ts]: Please remove debug message.

**Review by adrysn — APPROVED** [review]
LGTM. Please merge after removing debug message.

File: src/components/backend-ai-resource-policy-list.ts (hunk 1 above)
Comment (lizable) [reply src/components/backend-ai-resource-policy-list.ts]: Got it!
