### PR TITLE
fix: restrict admin only pages

### LINKED ISSUE #769: some administration pages is accessible to every user
**Describe the bug**
Although administration pages (such as Users, Environments, Resources, Configuration, etc.) allowed to admin and super-admin user only, every user can access to every pages by adding backlash in base url of Backend.AI GUI Console.

**To Reproduce**
1. Login with the common user account, not admin or supar-admin.
2. remove page keyword in url and type one of the keyword below in the behind of the url with backlash.
> credential
> environment
> agent
> settings
> maintenance
> information
3. See some pages are accessible with data.

**Expected behavior**
If non-admin user tries to access one of administration pages, page should show a warning that the user is unauthorized to access this page.

**Client:**
 - OS: macOS 10.15.6
 - App version: 20.11.0
 - Browser version: Firefox 82.0(64 bit)
 - NodeJS version: 13.8.0

**Server:**
 - OS: macOS 10.15.6
   - Output of `uname -a`: Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
 - Backend.AI version: 20.09.0a2
 - Python version: 3.8.3
 - Installation method: used scripts/install-dev.sh

### PR DESCRIPTION
**Pull request by lizable**
This PR resolves #769.

### CODE REVIEW

File: src/components/backend-ai-console.ts [hunk 1]
```diff
@@ -599,15 +618,14 @@ export default class BackendAIConsole extends connect(store)(LitElement) {
     if (changedProps.has('_page')) {
       let view: string = this._page;
       // load data for view
-      if (['summary', 'job', 'agent', 'credential', 'data', 'usersettings', 'environment', 'settings', 'maintenance', 'information', 'statistics', 'github', 'import'].includes(view) !== true) { // Fallback for Windows OS
-        let modified_view: (string | undefined) = view.split(/[\/]+/).pop();
-        if (typeof modified_view != 'undefined') {
-          view = modified_view;
-        } else {
-          view = 'summary';
+      if (this.availablePages.includes(view) !== true) { // Fallback for Windows OS
```
Comment (inureyes) [inline src/components/backend-ai-console.ts:624]: It is not a url filter but a Windows OS path monkey patch.

**Review by inureyes — APPROVED** [review]
