### PR TITLE
fix: resource group to match with resource statistics gauge

### LINKED ISSUE #811: Resource Group and resource statistics don't sync each other.
**Describe the bug**
Resource Group and resource statistics doesn't match after the user redirects to another pages and come back.

**To Reproduce**
1. Go to 'Summary' page.
2. Click on 'Resource Group' dropdown UI and select one except the one selected at first.
3. Go to 'Sessions' page.
4. Go to 'Summary' page.
5. See the error.

**Expected behavior**
Resource Group changes, then resource statistics should change, too.

**Screenshots**
resource-statistics-panel

**Client:**
- OS: macOS 10.15.6
- App version: 20.11.0
- Browser version: Firefox 82.0(64 bit)
- NodeJS version: 13.8.0

**Server:**
- OS: macOS 10.15.6
- Output of `uname -a`: Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-- 6153.141.1~1/RELEASE_X86_64 x86_64
- Backend.AI version: 20.09.0a2
- Python version: 3.8.3
- Installation method: used scripts/install-dev.sh

**Additional context**
Also, If the user selected another resource group, then It must be remained as is, before the user changes.

### PR DESCRIPTION
**Pull request by lizable**
This PR resolves #811.

### CODE REVIEW

File: src/components/backend-ai-resource-monitor.ts [hunk 1]
```diff
@@ -404,7 +404,7 @@ export default class BackendAiResourceMonitor extends BackendAIPage {
     this.resourceGauge = this.shadowRoot.querySelector('#resource-gauges');
     this._updateToggleResourceMonitorDisplay();
     document.addEventListener("backend-ai-group-changed", (e) => {
-      // this.scaling_group = '';
+      this.scaling_group = '';
```
Comment (inureyes) [inline src/components/backend-ai-resource-monitor.ts:407]: Please explain the reason why removing commented line. :) @lizable

**Review by inureyes — APPROVED** [review]
Good to go
