### PR TITLE
fix: disable app selection when session cancelled

### LINKED ISSUE #758: When session failed to start, App selection dialog still appears.
If session failed to start for some invalid vfolders mounting or old environment images(e.g. fortran) session status changes to prepared -> cancelled(failed to start), but It still shows app dialog with terminal. Let's show app dialog only if session successfully created.

### PR DESCRIPTION
**Pull request by lizable**
This PR resolves #758.

### CODE REVIEW

File: src/components/backend-ai-session-launcher.ts [hunk 1]
```diff
@@ -917,7 +917,12 @@ export default class BackendAiSessionLauncher extends BackendAIPage {
             appOptions['runtime'] = 'jupyter';
             appOptions['filename'] = this.importFilename;
           }
-          globalThis.appLauncher.showLauncher(appOptions);
+          // only launch app when it has valid service ports
+          if (service_info.length > 0) {
+            globalThis.appLauncher.showLauncher(appOptions);
+          } else {
+            throw { "message": _text('session.CreationFailed')}
+          }
```
Comment (adrysn) [inline src/components/backend-ai-session-launcher.ts]: In creating a kernel, session-launcher poses a [timeout (10 s)](https://github.com/lablup/backend.ai-console/blob/main/src/components/backend-ai-session-launcher.ts#L961) to wait for the return data from the server. However, there are cases where a session is running after 10 s. For example, there may be a bootstrap scripts which runs longer than 10 s. In those cases, it is inappropriate to display session creation is failed. In my opinion, it would rather better not to display anything.

**Review by adrysn — CHANGES_REQUESTED** [review]
I have comments on a minor message issue.

File: src/components/backend-ai-session-launcher.ts (hunk 1 above)
Comment (lizable) [reply src/components/backend-ai-session-launcher.ts]: Hmm, I thought that without notification, if the session was immediately removed from the running tab or moved to the exit tab, the user could be confused as to whether the session was successfully created or deleted.
However, I think this part could be solved in the other issue (#772), so I'll fix it as you suggested.

**Review by lizable — COMMENTED** [review]
I removed throwing error messages to prevent from showing error even if session was created successfully with delay as @adrysn suggested.

File: src/components/backend-ai-storage-list.ts [hunk 2]
```diff
@@ -1781,6 +1781,17 @@ export default class BackendAiStorageList extends BackendAIPage {
...
+   * Hide a wl dialog.
+   *
+   * @param {Event} e - Dispatches from the native input event each time the input changes.
+   */
+  _hideDialog(e) {
+    let hideButton = e.target;
+    let dialog = hideButton.closest('wl-dialog');
+    dialog.hide();
+  }
+
```
Comment (adrysn) [inline src/components/backend-ai-storage-list.ts]: Introduction `_hideDialog` prevents closing delete file dialog with Cancel button.

**Review by adrysn — CHANGES_REQUESTED** [review]
Cannot close file delete dialog with Cancel button.

File: src/components/backend-ai-storage-list.ts (hunk 2 above)
Comment (lizable) [reply src/components/backend-ai-storage-list.ts]: I just found out that _hideDialog is already implemented in the base class of BackendAiStorageList, which is BackendAIPage.
https://github.com/lablup/backend.ai-console/blob/0db0d2174f051193116e5fd3cc04c61f82f8c8ad/src/components/backend-ai-page.ts#L77-L85

Therefore, I'll remove `_hideDialog` function rightaway.

**Review by adrysn — APPROVED** [review]
LGTM.
