### PR TITLE
fix: vfolder name validation

### LINKED ISSUE #776: Vfolder creation/updating/deletion operation should be fixed.
**Describe the bug**
There are several bugs found in creating/updating/deleting operation of vfolder.
- C(create) vfolder:
    user can create vfolder when the folder name starts with alphabet or number or .(dot) only.
    If user tries to create vfolder with other character (e.g. korean) or tries to create vfolder starts with -(hyphen) or 
   _(underscore) It shows error.
- U(update) vfolder:
   It is the same as a problem that occurs when creating a vfolder.
- D(delete) vfolder:
   If the folder contains dot in the middle of folder name, input field shows that the value is invalid, but deleting request works.
   
**To Reproduce**
- In creating vfolder
1. Go to Data & Storage page.
2. Click 'NEW FOLDER' in the right top of the tab.
3. Creating dialog shows up.
4. Type other characters such as -(hyphen) or _(underscore) or other character except special character (e.g. korean) in the dialog.
5. See error.

- In updating(renaming) vfolder
1. Go to Data & Storage page.
2. Click rename icon in the row.
3. Renaming dialog shows up.
4. Type other characters such as -(hyphen) or _(underscore) or other character (e.g. korean) except special characters  in the dialog.
5. See error.

- In deleting vfolder
1. Go to Data & Storage page.
2. Click 'NEW FOLDER' in the right top of the tab.
3. create vfolder with folder name starts with .(dot) and put .(dot) once more in somewhere in the folder name.
    (e.g: .test.test)
4. Vfolder created.
5. Click image icon in the row of the vfolder that created in the step 3.
6. Deleting dialog shows up.
7. Type the folder name that created in the step 3.
8. See error.

**Expected behavior**
- In creating vfolder
folder should be created which starts with -(hyphen), or _(underscore) or any other character except special characters.

- In updating vfolder (renaming)
Updating folder name should work exactly same as creating a vfolder.

- In deleting vfolder
.(dot) including folder should not be treated as invalid, since It can be removed.

**Client:**
- OS: macOS 10.15.6
- App version: 20.11.0
- Browser version: Firefox 82.0(64 bit)
- NodeJS version: 13.8.0

**Server:**
- OS: macOS 10.15.6
- Output of `uname -a`: Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-- 6153.141.1~1/RELEASE_X86_64 x86_64
- Backend.AI version: 20.09.0a2
- Python version: 3.8.3
- Installation method: used scripts/install-dev.sh

### PR DESCRIPTION
**Pull request by lizable**
this PR resolves #776 .

### CODE REVIEW

File: src/components/backend-ai-data-view.ts [hunk 1]
```diff
@@ -273,8 +273,8 @@ export default class BackendAIData extends BackendAIPage {
       <backend-ai-dialog id="add-folder-dialog" fixed backdrop>
         <span slot="title">${_t("data.CreateANewStorageFolder")}</span>
         <div slot="content">
-          <mwc-textfield id="add-folder-name" label="${_t("data.Foldername")}" pattern="^[\.a-zA-Z0-9_-]+$"
-              auto-validate required validationMessage="${_t("data.Allowslettersnumbersand-_dot")}"></mwc-textfield>
+          <mwc-textfield id="add-folder-name" label="${_t("data.Foldername")}" @change="${() => this._validateFolderName()}"
```
Comment (inureyes) [inline src/components/backend-ai-data-view.ts:276]: _validateFolderName allows blank but it is not allowed on server. (it must be slug-type.)

**Review by inureyes — CHANGES_REQUESTED** [review]
It should not allow blank as folder name.
